<a href="https://colab.research.google.com/github/luisfernandorutti43-wq/Examen-Final-Te-rico/blob/main/FUNDAMENTOS%20Y%20ALGORITMIA%20PARA%20INTELIGENCIA%20ARTIFICIAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import pandas as pd
import math

print("="*60)
print("EXAMEN PRÁCTICO: FUNDAMENTOS Y ALGORITMIA PARA IA")
print("="*60)

EXAMEN PRÁCTICO: FUNDAMENTOS Y ALGORITMIA PARA IA


 PARTE 1: FUNDAMENTOS NUMPY

In [9]:
print("\nFUNDAMENTOS NUMPY")
print("-"*40)

# 1. Crear un arreglo NumPy de dimensión 1 con los números del 1 al 20
print("1. Arreglo NumPy del 1 al 20:")
arreglo_1_20 = np.arange(1, 21)
print(f"Arreglo: {arreglo_1_20}")

# 2. Seleccionar múltiplos de 3 de ese arreglo
print("\n2. Múltiplos de 3:")
multiplos_3 = arreglo_1_20[arreglo_1_20 % 3 == 0]
print(f"Múltiplos de 3: {multiplos_3}")

# 3. Generar una matriz aleatoria de tamaño 5x5 con números entre 0 y 1
print("\n3. Matriz aleatoria 5x5:")
np.random.seed(42)  # Para reproducibilidad
matriz_aleatoria = np.random.random((5, 5))
print(f"Matriz aleatoria 5x5:\n{matriz_aleatoria}")

# 4. Calcular la media, desviación estándar y valor máximo de esa matriz
print("\n4. Estadísticas de la matriz:")
media = np.mean(matriz_aleatoria)
desv_std = np.std(matriz_aleatoria)
valor_max = np.max(matriz_aleatoria)
print(f"Media: {media:.4f}")
print(f"Desviación estándar: {desv_std:.4f}")
print(f"Valor máximo: {valor_max:.4f}")

# 5. Transformar la matriz en un vector de una sola dimensión
print("\n5. Vector de una dimensión:")
vector = matriz_aleatoria.flatten()
print(f"Vector: {vector}")


FUNDAMENTOS NUMPY
----------------------------------------
1. Arreglo NumPy del 1 al 20:
Arreglo: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

2. Múltiplos de 3:
Múltiplos de 3: [ 3  6  9 12 15 18]

3. Matriz aleatoria 5x5:
Matriz aleatoria 5x5:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]

4. Estadísticas de la matriz:
Media: 0.4408
Desviación estándar: 0.2795
Valor máximo: 0.9699

5. Vector de una dimensión:
Vector: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
 0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643
 0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184
 0.45606998]


PARTE 2: FUNDAMENTOS PANDAS

In [10]:
print("\n\nFUNDAMENTOS PANDAS")
print("-"*40)

# 1. Crear DataFrame con datos de estudiantes
print("1. DataFrame de estudiantes:")
datos_estudiantes = {
    'Nombre': ['Ana', 'Luis', 'María', 'Pedro', 'Sofía'],
    'Edad': [20, 21, 19, 22, 20],
    'Nota_Matematicas': [18, 15, 16, 12, 19],
    'Nota_IA': [17, 14, 18, 13, 20]
}
df_estudiantes = pd.DataFrame(datos_estudiantes)
print(df_estudiantes)

# 2. Calcular el promedio de cada columna numérica
print("\n2. Promedio de columnas numéricas:")
promedios = df_estudiantes[['Edad', 'Nota_Matematicas', 'Nota_IA']].mean()
print(promedios)

# 3. Filtrar estudiantes con nota de IA mayor a 15
print("\n3. Estudiantes con Nota_IA > 15:")
estudiantes_filtrados = df_estudiantes[df_estudiantes['Nota_IA'] > 15]
print(estudiantes_filtrados)

# 4. Agregar columna Promedio
print("\n4. DataFrame con columna Promedio:")
df_estudiantes['Promedio'] = (df_estudiantes['Nota_Matematicas'] + df_estudiantes['Nota_IA']) / 2
print(df_estudiantes)

# 5. Ordenar DataFrame según columna Promedio de mayor a menor
print("\n5. DataFrame ordenado por Promedio (mayor a menor):")
df_ordenado = df_estudiantes.sort_values('Promedio', ascending=False)
print(df_ordenado)




FUNDAMENTOS PANDAS
----------------------------------------
1. DataFrame de estudiantes:
  Nombre  Edad  Nota_Matematicas  Nota_IA
0    Ana    20                18       17
1   Luis    21                15       14
2  María    19                16       18
3  Pedro    22                12       13
4  Sofía    20                19       20

2. Promedio de columnas numéricas:
Edad                20.4
Nota_Matematicas    16.0
Nota_IA             16.4
dtype: float64

3. Estudiantes con Nota_IA > 15:
  Nombre  Edad  Nota_Matematicas  Nota_IA
0    Ana    20                18       17
2  María    19                16       18
4  Sofía    20                19       20

4. DataFrame con columna Promedio:
  Nombre  Edad  Nota_Matematicas  Nota_IA  Promedio
0    Ana    20                18       17      17.5
1   Luis    21                15       14      14.5
2  María    19                16       18      17.0
3  Pedro    22                12       13      12.5
4  Sofía    20                19 

PARTE 3: ALGORITMIA APLICADA

In [11]:
print("\n\nALGORITMIA APLICADA")
print("-"*40)

# 1. Función que devuelve el número mayor, menor y promedio
def analizar_lista(numeros):
    """
    Función que recibe una lista de números y devuelve:
    - El número mayor
    - El número menor
    - El promedio
    """
    if not numeros:
        return None, None, None

    numero_mayor = max(numeros)
    numero_menor = min(numeros)
    promedio = sum(numeros) / len(numeros)

    return numero_mayor, numero_menor, promedio

print("1. Función para analizar lista de números:")
lista_ejemplo = [5, 12, 3, 8, 15, 1, 9]
mayor, menor, prom = analizar_lista(lista_ejemplo)
print(f"Lista: {lista_ejemplo}")
print(f"Mayor: {mayor}, Menor: {menor}, Promedio: {prom:.2f}")

# 2. Función de activación Sigmoide
def funcion_sigmoide(x):
    """
    Implementa la función de activación Sigmoide
    f(x) = 1 / (1 + e^(-x))
    """
    return 1 / (1 + np.exp(-x))

print("\n2. Función de activación Sigmoide:")
x_array = np.array([-2, -1, 0, 1, 2])
resultado_sigmoide = funcion_sigmoide(x_array)
print(f"x = {x_array}")
print(f"f(x) = {resultado_sigmoide}")

# 3. Función para clasificar estudiantes
def clasificar_estudiantes(df, columna_promedio='Promedio'):
    """
    Clasifica estudiantes en 'Aprobado' si Promedio >= 14,
    'Desaprobado' en caso contrario
    """
    df_copia = df.copy()
    df_copia['Estado'] = df_copia[columna_promedio].apply(
        lambda x: 'Aprobado' if x >= 14 else 'Desaprobado'
    )
    return df_copia

print("\n3. Clasificación de estudiantes:")
df_clasificado = clasificar_estudiantes(df_estudiantes)
print(df_clasificado[['Nombre', 'Promedio', 'Estado']])




ALGORITMIA APLICADA
----------------------------------------
1. Función para analizar lista de números:
Lista: [5, 12, 3, 8, 15, 1, 9]
Mayor: 15, Menor: 1, Promedio: 7.57

2. Función de activación Sigmoide:
x = [-2 -1  0  1  2]
f(x) = [0.11920292 0.26894142 0.5        0.73105858 0.88079708]

3. Clasificación de estudiantes:
  Nombre  Promedio       Estado
0    Ana      17.5     Aprobado
1   Luis      14.5     Aprobado
2  María      17.0     Aprobado
3  Pedro      12.5  Desaprobado
4  Sofía      19.5     Aprobado


PARTE 4: MINI-PROYECTO

In [12]:
print("\n\n MINI-PROYECTO")
print("-"*40)

# Dataset simulado de ventas
datos = {
    'Producto': ['A', 'B', 'C', 'D', 'E'],
    'Ventas_2024': [120, 340, 560, 230, 150],
    'Ventas_2025': [200, 400, 600, 300, 180]
}
df = pd.DataFrame(datos)

print("Dataset original:")
print(df)

# 1. Agregar columna Crecimiento (porcentaje)
print("\n1. Agregando columna Crecimiento:")
df['Crecimiento'] = ((df['Ventas_2025'] - df['Ventas_2024']) / df['Ventas_2024'] * 100).round(2)
print(df)

# 2. Identificar producto con mayor crecimiento
print("\n2. Producto con mayor crecimiento:")
producto_mayor_crecimiento = df.loc[df['Crecimiento'].idxmax()]
print(f"Producto: {producto_mayor_crecimiento['Producto']}")
print(f"Crecimiento: {producto_mayor_crecimiento['Crecimiento']}%")



 MINI-PROYECTO
----------------------------------------
Dataset original:
  Producto  Ventas_2024  Ventas_2025
0        A          120          200
1        B          340          400
2        C          560          600
3        D          230          300
4        E          150          180

1. Agregando columna Crecimiento:
  Producto  Ventas_2024  Ventas_2025  Crecimiento
0        A          120          200        66.67
1        B          340          400        17.65
2        C          560          600         7.14
3        D          230          300        30.43
4        E          150          180        20.00

2. Producto con mayor crecimiento:
Producto: A
Crecimiento: 66.67%


PARTE 5: RESOLUCIÓN DE ECUACIONES

In [13]:
print("\n\nRESOLUCIÓN DE ECUACIONES")
print("-"*40)

# 1. Ecuación de primer grado: ax + b = 0
def resolver_ecuacion_primer_grado(a, b):
    """
    Resuelve ecuación de primer grado: ax + b = 0
    Retorna el valor de x
    """
    if a == 0:
        if b == 0:
            return "Infinitas soluciones"
        else:
            return "No tiene solución"
    else:
        x = -b / a
        return x

print("1. Ecuación de primer grado:")
print("Ejemplo: 2x + 4 = 0")
solucion_1 = resolver_ecuacion_primer_grado(2, 4)
print(f"Solución: x = {solucion_1}")

# 2. Ecuación de segundo grado: ax² + bx + c = 0
def resolver_ecuacion_segundo_grado(a, b, c):
    """
    Resuelve ecuación de segundo grado usando la fórmula general:
    x = (-b ± √(b² - 4ac)) / 2a
    Retorna las dos soluciones (reales o complejas)
    """
    if a == 0:
        return "No es ecuación de segundo grado"

    discriminante = b**2 - 4*a*c

    if discriminante >= 0:
        x1 = (-b + math.sqrt(discriminante)) / (2*a)
        x2 = (-b - math.sqrt(discriminante)) / (2*a)
        return x1, x2
    else:
        # Soluciones complejas
        real_part = -b / (2*a)
        imag_part = math.sqrt(-discriminante) / (2*a)
        x1 = complex(real_part, imag_part)
        x2 = complex(real_part, -imag_part)
        return x1, x2

print("\n2. Ecuación de segundo grado:")
print("Ejemplo: x² - 5x + 6 = 0")
sol1, sol2 = resolver_ecuacion_segundo_grado(1, -5, 6)
print(f"Soluciones: x1 = {sol1}, x2 = {sol2}")

print("\nEjemplo con discriminante negativo: x² + x + 1 = 0")
sol1_c, sol2_c = resolver_ecuacion_segundo_grado(1, 1, 1)
print(f"Soluciones complejas: x1 = {sol1_c}, x2 = {sol2_c}")

print("\n" + "="*60)
print("EXAMEN COMPLETADO")
print("="*60)



RESOLUCIÓN DE ECUACIONES
----------------------------------------
1. Ecuación de primer grado:
Ejemplo: 2x + 4 = 0
Solución: x = -2.0

2. Ecuación de segundo grado:
Ejemplo: x² - 5x + 6 = 0
Soluciones: x1 = 3.0, x2 = 2.0

Ejemplo con discriminante negativo: x² + x + 1 = 0
Soluciones complejas: x1 = (-0.5+0.8660254037844386j), x2 = (-0.5-0.8660254037844386j)

EXAMEN COMPLETADO
